### PR TITLE
Dockerfile: Add mwitkow/go-proto-validators

### PR DESCRIPTION
**Pull request by keinohguchi**
Add support for `--govalidators_out` option, as `--govalidators_out=gogoimport=true:.`

### CODE REVIEW

**Comment by keinohguchi** [comment]
Thanks @QuentinPerez for :+1:.  Looking forward to the merge as well as the docker image on dockerhub, so that I can replace the image from my local one to the public one on dockerhub.

**Comment by keinohguchi** [comment]
Hi @QuentinPerez, I've added additional commit to include the validator protobuf file into the image.

By the way, here is the image I'm using for our build process, which contains those two commits:

https://hub.docker.com/r/keinohguchi/protoc/

**Comment by QuentinPerez** [comment]
Thx @keinohguchi, cc @steeve

**Comment by keinohguchi** [comment]
Thanks @QuentinPerez and @steeve!  I'll use my private docker image for our use but love to see it in your dockerhub, so that we're in sync with the upstream.

Thank you so much for sharing this usuful container!

**Comment by keinohguchi** [comment]
Seems @steeve is busy with something.  I'll go with my special image for now but looking forward to see the merge as well as the new image with the `go-proto-validators` support.

Great job, @QuentinPerez and @steeve!

**Comment by steeve** [comment]
Sorry for the lag, I was on vacation, thanks @QuentinPerez for keeping up !

**Pull request merged**
