### PR TITLE
Rollback UPX compression (regression)

### PR DESCRIPTION
**Pull request by moul**
Addresses #13

### CODE REVIEW

**Comment by steeve** [comment]
I should only reverse grpc-java imho

**Comment by moul** [comment]
up

**Comment by moul** [comment]
up (see https://github.com/znly/docker-protobuf/issues/13#issuecomment-261979568)

**Comment by steeve** [comment]
Sigh... LGTM

**Comment by moul** [comment]
:) @QuentinPerez, your mission is to make @steeve happy again !

**Pull request merged**
