### PR TITLE
Save 150M and update README

### PR DESCRIPTION
**Pull request by QuentinPerez**
```
docker images 
znl/protoc            latest              b60605635ef9        27 minutes ago      134.5 MB <- after
znly/protoc           latest              49138f65a9bf        43 minutes ago      286.6 MB <- before
```

### CODE REVIEW

**Comment by steeve** [comment]
How does this work?
I thought `find /usr/lib -name "*.a" -or -name "*.la" -delete` would do the trick

**Comment by steeve** [comment]
Indeed it works. Can you update the README and change the image size ?

**Comment by QuentinPerez** [comment]
This command remove only `*.la` to delete `*.a` and `*.la` -> `find /usr/lib -name "*.a" -delete -or -name "*.la" -delete`

```
find /usr/lib -name "*.a" -or -name "*.la" -delete
/ # find /usr/lib -name "*.a" -or -name "*.la"
/usr/lib/libprotobuf-lite.a
/usr/lib/libprotobuf.a
/usr/lib/libprotoc.a
/ # find /usr/lib -name "*.a" -delete -or -name "*.la" -delete
/ # find /usr/lib -name "*.a" -or -name "*.la"
/ #
```

**Comment by steeve** [comment]
ah shit. good call.

Can you add `-delete` to the find and update the README with the new size ?

**Comment by QuentinPerez** [comment]
done 😊 👍

**Comment by steeve** [comment]
awesome!

**Pull request merged**
